# Fill in the path belows with your own specifications:
workdir:                    # Path to output directory
blast_db:                   # Path to BLAST-formated database
taxdb:                      # Path to the folder containing the taxdb files
samples:                    # Path to the sample definition table

# Modify the parameters below:
read_length: 150            # Sequencing read length
mean_fragment_size: 151     # Mean DNA fragment size. Must be > than read_length
quality_shift_R2: 0        # Quality shift of read 2
fragment_size_sdev: 0       # Standard deviation of fragment size
seq_system: MSv3            # Sequencing system, ignored if providing custom profiles
quality_profile_read1: None # Custom quality profile for read1
quality_profile_read2: None # Custom quality profile for read2


